name: variant-remapping
channels:
  - bioconda
  - defaults
dependencies:
  - bedtools=2.29.2
  - minimap2=2.1
  - samtools=1.9
  - bcftools=1.9
  - bedops=2.4.39
  - tabix=0.2.6
  - nextflow=20.07.1
