name: Variant Remapping

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Install dependencies
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file conda.yml --name base --yes
        $CONDA/bin/conda run pip install -q -r requirements.txt

    - name: Test nextflow workflow
      run:
        $CONDA/bin/conda run tests/test_pipeline.sh

    - name: Test with pytest
      run:
        $CONDA/bin/conda run PYTHONPATH=. pytest variant_remapping_tools/tests
